# Generated by Django 6.0.4 on 2026-05-04 22:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('color', models.CharField(db_column='color', max_length=20)),
            ],
            options={
                'db_table': 'estados_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='nombre_tipo', max_length=100)),
                ('dias_alerta', models.IntegerField(db_column='dias_alerta', default=30)),
            ],
            options={
                'db_table': 'tipos_documentos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('empleado', 'empleado')], db_column='rol', default='empleado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(db_column='id_documento', primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='fecha_vencimiento', null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('fecha_detencion', models.DateField(blank=True, db_column='fecha_detencion', null=True)),
                ('archivo', models.FileField(blank=True, db_column='archivo', null=True, upload_to='documentos/')),
                ('nombre_archivo', models.CharField(blank=True, db_column='nombre_archivo', max_length=255, null=True)),
                ('tipo_mime', models.CharField(blank=True, db_column='tipo_mime', max_length=100, null=True)),
                ('tamano', models.IntegerField(blank=True, db_column='tamano', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.cliente')),
                ('creado_por', models.ForeignKey(db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(db_column='modificado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_modificados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='id_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_clientes.estadodocumento')),
                ('tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.tipodocumento')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id_historial', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(db_column='estado_anterior', max_length=50)),
                ('estado_nuevo', models.CharField(db_column='estado_nuevo', max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='fecha_cambio')),
                ('comentario', models.TextField(blank=True, db_column='comentario', null=True)),
                ('documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.documento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_documentos',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(db_column='id_log', primary_key=True, serialize=False)),
                ('accion', models.CharField(db_column='accion', max_length=100)),
                ('tabla_afectada', models.CharField(db_column='tabla_afectada', max_length=50)),
                ('id_registro', models.IntegerField(db_column='id_registro')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(db_column='id_notificacion', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(db_column='mensaje')),
                ('tipo', models.CharField(choices=[('alerta', 'alerta'), ('vencido', 'vencido')], db_column='tipo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('enviado', models.BooleanField(db_column='enviado', default=False)),
                ('documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.documento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='id_reporte', primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(db_column='tipo_reporte', max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fecha_generacion')),
                ('parametros', models.JSONField(db_column='parametros')),
                ('generado_por', models.ForeignKey(db_column='generado_por', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id_config', models.AutoField(db_column='id_config', primary_key=True, serialize=False)),
                ('dias_rojo', models.IntegerField(db_column='dias_rojo')),
                ('dias_amarillo', models.IntegerField(db_column='dias_amarillo')),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.tipodocumento')),
            ],
            options={
                'db_table': 'configuracion_alertas',
            },
        ),
    ]
